# Generated by Django 4.0.3 on 2022-06-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='opd_pfsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_medical_history', models.CharField(max_length=500)),
                ('family_medical_history', models.CharField(max_length=500)),
                ('opdpfsh_UHID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homepage.homepagemodel')),
            ],
        ),
    ]
